package com.tcs.beans;

// Generated Jun 24, 2014 3:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Userdetails generated by hbm2java
 */
public class UserDetails implements java.io.Serializable {

	private long id;
	private String name;
	private String gender;
	private String country;
	private String aboutyou;
	private Boolean mailinglist;

	public UserDetails() {
	}
	
	public UserDetails(long id ) {
		this.id=id;
	}

	
	public UserDetails(long id, String name, String gender,
			String country, String aboutyou, Boolean mailinglist) {
		this.id = id;
		this.name = name;
		this.gender = gender;
		this.country = country;
		this.aboutyou = aboutyou;
		this.mailinglist = mailinglist;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getAboutyou() {
		return this.aboutyou;
	}

	public void setAboutyou(String aboutyou) {
		this.aboutyou = aboutyou;
	}

	public Boolean getMailinglist() {
		return this.mailinglist;
	}

	public void setMailinglist(Boolean mailinglist) {
		this.mailinglist = mailinglist;

	}

}
